# fly.toml app configuration file generated for ruh-frontend-app on 2025-07-15T14:48:45+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ruh-frontend-app'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
